config/routes.rb
Blog::Application.routes.draw do
 
 resources :articles do
  resources :comments
end

  root 'articles#new'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many  :comments
	validates :title , presence:true ,length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
	def new
		@article=Article.new
	end
	
	def create
	redirect_to root_url 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
@article= Article.new
  end

  def index
  end

  def create
   #@article =Article.new
    #Article.create(article_params)
  
  #redirect_to 'articles_new_path'
  @article= Article.new(article_params)
  
         if  @article.save
          #redirect_to new_article_path
         redirect_to @article
          else 
          render 'new'
         #redirect_to root_path
      end


  end

  def edit
    @article= Article.find(params[:id])
  end

  
  def destroy
     @article= Article.find(params[:id])
     @article.destroy
     redirect_to root_path
  end

  def show
    @article = Article.find(params[:id])
    

  end

  def update
   @article = Article.find(params[:id])
   @article.update_attributes(article_params)
   redirect_to @article
 end
 def index
  @article= Article.find(:all)

 end
  private
    def article_params
      params.require(:article).permit(:title,:text)
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def create
   @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    #redirect_to article_path(@article)
    redirect_to @article
  end

  def show
    
  end

  def edit
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end

  def update
     @article = Article.find(params[:article_id])
    @comment= @article.comments.find(params[:id])
    @comment.update_attributes(comment_params)
    redirect_to @article
  end
  def destroy
    @article= Article.find(params[:article_id])
    @comment= @article.comments.find(params[:id])
    @comment.destroy
    redirect_to @article
  end

  def new
    
  end
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@name = "asd"
  	@name=Time.now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/article/new.html.erb
<%= form_for :article do |f| %>
<p>
<%= f.label :title%>
<%= f.text_field :title%>
</p>
<p>
<%= f.label :text %>
<%= f.text_area :text %>
</p>
<p>
<%= f.submit%>
</p>
<%end%>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/delete.html.erb
<h1>Articles#delete</h1>
<p>Find me in app/views/articles/delete.html.erb</p>

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>
<p>
<%= f.label :title%>
<%= f.text_field :title%>
</p>
<p>
<%= f.label :text %>
<%= f.text_area :text %>
</p>
<p>
<%= f.submit %>
</p>
<%end%>

app/views/articles/index.html.erb
<%=@article.each do |article|%>
<p> Title: <%= article.title %>
</p>
<p> Text: <%= article.text %>
</p>
<%end%>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
<% if @article.errors.any? %>
<h1><%= pluralize(@article.errors.count, "error")%>
prohibited this article from being saved </h1>
<ul>
<% @article.errors.full_messages.each do |msg| %>
<li> <%=msg%> </li>
<%end%>
</ul>
<%end%>
<p>
<%= f.label :title%>
<%= f.text_field :title%>
</p>
<p>
<%= f.label :text %>
<%= f.text_area :text %>
</p>
<p>
<%= f.submit%>
</p>
<%end%>

app/views/articles/show.html.erb
<p>TITLE:::</p>
<%= @article.title %>
<p>TEXT::::::::::</p>
<%= @article.text %>
<%=link_to "Edit", edit_article_path(@article) %>
<%=link_to "Delete", @article, method: :delete %>
<%= link_to "Index", articles_path %>
<%= link_to "New", new_article_path %>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  
| <%= link_to 'Edit', edit_article_comment_path(@article, comment) %>
 <%= link_to 'Delete', article_comment_path(@article, comment), method: :Delete%>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<%= form_for([@article, @comment]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1> i am here</h1>
<%= @name %>